### ISSUE TITLE
Re alocate arrow pointing

### ISSUE THREAD

**Issue by sebasvp2005** [sebasvp2005/StronglyConnectedComponents_Simulator#1]

**Comment by JGhostM** [comment]
def draw_graph(self):
        self.graph_canva.delete("all")
        self.components_canva.delete("all")
        nodes =[[] for i in range(self.dimension)]
        location = [[random.randint(50, 420), random.randint(10, 170)] for i in range(self.dimension)]
        for i in range(self.dimension):
            for j in range(self.dimension):
                if i == j:
                    continue
                if self.matrix[i][j].isactive(): 
                    nodes[i].append(j)
                    #location[i][1] - location [j][1] / location [i][0] - location [j][1] = pendiente
                     #cos(q) * hypo(hypotenusa) = x
                     #sen(q) * hypo = y
                     #new position

                    dx = location[i][0] - location [j][0]
                    dy = location [i][1] - location [j][1]

                    pendiente = dy / dx

                    q = math.atan(pendiente)
                    hypo = 7.5

                    x = math.cos(q) * hypo
                    y = math.sin(q) * hypo

                    self.graph_canva.create_line(location[i][0]+7, location[i][1]+7, location[j][0]+7+x, location[j][1]+7+y, arrow=LAST,fill='white', )

        for x,y in location:
            self.graph_canva.create_oval(x,y, x+15, y+15, fill='white', outline='black')

        components = controller.get_strongly_connectec_components(nodes)

        for group in components:
            q =[group[0]]
            v = [False] * self.dimension
            v[group[0]]=True
            while len(q):
                temp  = q.pop(0)
                for e in nodes[temp]:
                    if e in group:
                        self.components_canva.create_line(location[temp][0]+7, location[temp][1]+7, location[e][0]+7, location[e][1]+7, arrow=LAST, fill='white')
                        if v[e]==0: 
                            q.append(e)
                            v[e]=1

        for x,y in location:
            self.components_canva.create_oval(x,y, x+15, y+15, fill='white', outline='black')

        self.label_ans.config(text=f'{len(components)}')

**Comment by JGhostM** [comment]
def draw_graph(self):
        self.graph_canva.delete("all")
        self.components_canva.delete("all")
        nodes =[[] for i in range(self.dimension)]
        location = [[random.randint(50, 420), random.randint(10, 170)] for i in range(self.dimension)]
        for i in range(self.dimension):
            for j in range(self.dimension):
                if i == j:
                    continue
                if self.matrix[i][j].isactive(): 
                    nodes[i].append(j)
                    #location[i][1] - location [j][1] / location [i][0] - location [j][1] = pendiente
                     #cos(q) * hypo(hypotenusa) = x
                     #sen(q) * hypo = y
                     #new position

                    dx = location[i][0] - location [j][0]
                    dy = location [i][1] - location [j][1]

                    pendiente = dy / dx

                    q = math.atan(pendiente)
                    hypo = 7.5

                    x = math.cos(q) * hypo
                    y = math.sin(q) * hypo

                    self.graph_canva.create_line(location[i][0]+7, location[i][1]+7, location[j][0]+7+x, location[j][1]+7+y, arrow=LAST,fill='white', )

        for x,y in location:
            self.graph_canva.create_oval(x,y, x+15, y+15, fill='white', outline='black')

        components = controller.get_strongly_connectec_components(nodes)

        for group in components:
            q =[group[0]]
            v = [False] * self.dimension
            v[group[0]]=True
            while len(q):
                temp  = q.pop(0)
                for e in nodes[temp]:
                    if e in group:
                        self.components_canva.create_line(location[temp][0]+7, location[temp][1]+7, location[e][0]+7, location[e][1]+7, arrow=LAST, fill='white')
                        if v[e]==0: 
                            q.append(e)
                            v[e]=1

        for x,y in location:
            self.components_canva.create_oval(x,y, x+15, y+15, fill='white', outline='black')

        self.label_ans.config(text=f'{len(components)}')

**Comment by sebasvp2005** [comment]
Realocation based on trigonometry identities
